/**
 * The definition-of-done gate.
 *
 * A VPN split-tunneling client asks the catalog one question: "which installed
 * packages should bypass the tunnel?" Getting a global app into that set is the
 * failure mode this whole project exists to prevent, so these are the tests that
 * must never be deleted: the named confusables have to stay out of every
 * per-country catalog and out of every generated bypass set, in every country.
 */

import assert from "node:assert/strict";
import test from "node:test";
import { buildAllBundle, buildCountryBundle } from "../tools/lib/bundle.mjs";
import { loadRepo } from "../tools/lib/load.mjs";
import { validateRepo } from "../tools/lib/rules.mjs";
import { CONFUSABLES, entry, makeRepo, readJson } from "./helpers.mjs";

const REPO = loadRepo();
const ALL = buildAllBundle(REPO, { release: "v2026.10.07" });

test("every confusable named in the spec is in the negative catalog", () => {
  const global = new Set(readJson("data/global.json").packages.map((p) => p.package));
  for (const { name, package: pkg } of CONFUSABLES) {
    assert.ok(global.has(pkg), `${name} (${pkg}) is missing from data/global.json`);
  }
});

test("no confusable appears in any country catalog, as payload or as entry", () => {
  const confusablePackages = new Set(CONFUSABLES.map((c) => c.package));
  for (const country of REPO.countries) {
    const bundle = buildCountryBundle(REPO, country.code, { release: "v2026.10.07" });
    const listed = new Set(Object.values(bundle.packages).flat());
    for (const app of bundle.entries) listed.add(app.package);
    for (const pkg of confusablePackages) {
      assert.ok(!listed.has(pkg), `${country.code} claims the global app ${pkg} as local`);
    }
  }
});

test("a device full of confusables selects an empty bypass set", () => {
  // Exactly the client decision: installed packages ∩ catalog packages.
  const installed = [
    ...CONFUSABLES.map((c) => c.package),
    "com.example.unrelated",
  ];
  for (const country of ALL.countries) {
    const local = new Set(Object.values(ALL.countries_detail[country].packages).flat());
    const bypass = installed.filter((pkg) => local.has(pkg));
    assert.deepEqual(bypass, [], `${country} would bypass the tunnel for ${bypass.join(", ")}`);
  }
});

test("a device with local apps gets just those, never a global app alongside them", () => {
  const country = "IR";
  const local = new Set(Object.values(ALL.countries_detail[country].packages).flat());
  assert.ok(local.size > 0, "expected IR to have local apps to test with");
  const installed = [...local, ...CONFUSABLES.map((c) => c.package)];
  const bypass = installed.filter((pkg) => local.has(pkg)).sort();
  assert.deepEqual(bypass, [...local].sort());
  for (const { package: pkg } of CONFUSABLES) assert.ok(!bypass.includes(pkg));
});

test("the validator refuses every confusable submitted as a local app", () => {
  for (const { name, package: pkg } of CONFUSABLES) {
    const repo = makeRepo({
      "ir/banking.json": {
        country: "IR",
        category: "banking",
        apps: [entry({ package: pkg })],
      },
    });
    try {
      const result = validateRepo(loadRepo({ dataDir: repo.dir }));
      assert.ok(
        result.errors.some((e) => e.code === "GLOBAL_CONFLICT"),
        `${name} was accepted as a local app`,
      );
    } finally {
      repo.cleanup();
    }
  }
});

test("the negative catalog is itself reachable from every bundle", () => {
  for (const country of ALL.countries) {
    const bundle = buildCountryBundle(REPO, country, { release: "v2026.10.07" });
    assert.equal(bundle.counts.globals, ALL.globals.length);
  }
});
